#!/bin/bash

# Setup Script untuk VPS/GCP
# Bot WhatsApp Renungan Harian v6.0 - Baileys (No Chromium!)
# Sangat ringan: ~100MB RAM, tanpa browser

echo "========================================="
echo "  Setup Bot Renungan v6.0 (Baileys)"
echo "  No Chromium - Ultra Lightweight"
echo "========================================="
echo ""

# 1. Update system
echo "📦 Updating system packages..."
sudo apt update && sudo apt upgrade -y

# 2. Install Node.js 20 (LTS)
echo "📦 Installing Node.js 20 LTS..."
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt install -y nodejs
echo "✅ Node.js: $(node -v)"

# 3. Install PM2
echo "📦 Installing PM2..."
sudo npm install -g pm2
echo "✅ PM2 installed"

# 4. Install Cloudflared (Cloudflare Tunnel) - optional
echo "📦 Installing Cloudflared..."
ARCH=$(uname -m)
if [ "$ARCH" = "x86_64" ]; then
    CF_ARCH="amd64"
elif [ "$ARCH" = "aarch64" ]; then
    CF_ARCH="arm64"
elif [ "$ARCH" = "armv7l" ]; then
    CF_ARCH="arm"
else
    echo "⚠️ Unsupported architecture: $ARCH"
    CF_ARCH=""
fi

if [ -n "$CF_ARCH" ]; then
    curl -L --output cloudflared.deb "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${CF_ARCH}.deb"
    sudo dpkg -i cloudflared.deb
    rm cloudflared.deb
    echo "✅ Cloudflared installed: $(cloudflared --version 2>&1)"
else
    echo "⚠️ Skipping cloudflared (install manually if needed)"
fi

# 5. Setup Swap (512MB - cukup untuk Baileys)
echo "💾 Setting up 512MB Swap..."
if [ ! -f /swapfile ]; then
    sudo fallocate -l 512M /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
    echo "✅ Swap 512MB created"
else
    echo "⚠️ Swap already exists"
fi

# 6. Optimize swappiness
echo "⚙️ Optimizing swappiness..."
sudo sysctl vm.swappiness=10
echo 'vm.swappiness=10' | sudo tee -a /etc/sysctl.conf 2>/dev/null

# 7. Install dependencies
echo "📦 Installing Node.js dependencies..."
npm install --production

# 8. Setup environment variables
echo "⚙️ Setting up environment variables..."
if [ ! -f .env ]; then
    echo "Creating .env file..."
    cat > .env << 'EOF'
# ============================================
# Generated by setup-gcp.sh (Baileys v6.0)
# ============================================

TIMEZONE=Asia/Makassar

# Telegram Bot
TELEGRAM_BOT_TOKEN=your_telegram_bot_token_from_botfather
ADMIN_TELEGRAM_IDS=123456789

# Webhook (via Cloudflare Tunnel) - hemat bandwidth
# WEBHOOK_URL=https://your-tunnel-subdomain.yourdomain.com
# WEBHOOK_PORT=3000

# AI Provider - Custom OpenAI-Compatible
AI_API_KEY=your_api_key_here
AI_API_ENDPOINT=http://your-endpoint/v1
AI_MODEL=gemini/gemini-2.5-flash-lite

# Renungan
RENUNGAN_GROUP_ID=
RENUNGAN_TIME=08:00
EOF
    echo "⚠️ Please edit .env file with your credentials!"
    echo "   Run: nano .env"
else
    echo "✅ .env already exists"
fi

# 9. Create logs directory
echo "📁 Creating logs directory..."
mkdir -p logs

echo ""
echo "========================================="
echo "✅ Setup completed!"
echo "========================================="
echo ""
echo "📊 Memory status:"
free -h
echo ""
echo "🚀 Cara menjalankan:"
echo "   npm start              # Development"
echo "   pm2 start ecosystem.config.js  # Production"
echo ""
echo "🌐 Setup Cloudflare Tunnel (opsional):"
echo "   bash setup.sh          # Interactive wizard"
echo ""
echo "⚙️  Edit konfigurasi:"
echo "   nano .env"
echo ""
