@echo off
setlocal enabledelayedexpansion

:: ============================================
:: JhopanWa Bot - Setup Wizard (Windows)
:: One-command setup: Cloudflare Tunnel + Bot
:: ============================================

title JhopanWa Bot Setup Wizard

echo.
echo ╔═══════════════════════════════════════════════════╗
echo ║     JhopanWa Bot - Setup Wizard (Windows)         ║
echo ║     Baileys + Cloudflare Tunnel                   ║
echo ╚═══════════════════════════════════════════════════╝
echo.

:: State file for rerun safety
set STATE_FILE=.setup-state

:: ============================================
:: STEP 1: Check Prerequisites
:: ============================================
echo.
echo --- Step 1/5: Checking prerequisites ---
echo.

:: Check Node.js
where node >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo [ERROR] Node.js not found!
    echo   Download from: https://nodejs.org/
    echo   Required: Node.js >= 20
    goto :fail
)
for /f "tokens=*" %%i in ('node -v') do set NODE_VER=%%i
echo   [OK] Node.js %NODE_VER%

:: Check npm
where npm >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo [ERROR] npm not found!
    goto :fail
)
for /f "tokens=*" %%i in ('npm -v') do set NPM_VER=%%i
echo   [OK] npm %NPM_VER%

:: Check cloudflared (optional)
set HAS_CLOUDFLARED=false
where cloudflared >nul 2>nul
if %ERRORLEVEL% equ 0 (
    for /f "tokens=*" %%i in ('cloudflared --version 2^>^&1') do set CF_VER=%%i
    echo   [OK] cloudflared !CF_VER!
    set HAS_CLOUDFLARED=true
) else (
    echo   [WARN] cloudflared not installed (optional - for webhook mode)
)

echo   [OK] Prerequisites check done

:: ============================================
:: STEP 2: Configuration
:: ============================================
echo.
echo --- Step 2/5: Configuration ---
echo.

:: Check if .env exists
set USE_EXISTING=false
if exist ".env" (
    set /p use_env="  .env already exists. Use existing config? (Y/n): "
    if /i "!use_env!" neq "n" (
        set USE_EXISTING=true
        echo   [OK] Using existing .env
    )
)

if "!USE_EXISTING!"=="false" (
    echo.
    echo   Bot Configuration:
    echo.

    :: Telegram Bot Token
    :tg_token
    set /p TG_TOKEN="  Telegram Bot Token (dari @BotFather): "
    if "!TG_TOKEN!"=="" (
        echo   [ERROR] Token tidak boleh kosong
        goto :tg_token
    )

    :: AI API Endpoint
    set /p AI_ENDPOINT="  AI API Endpoint [https://your-api-endpoint.com/v1]: "
    if "!AI_ENDPOINT!"=="" set AI_ENDPOINT=https://your-api-endpoint.com/v1

    :: AI API Key
    :ai_key
    set /p AI_KEY="  AI API Key: "
    if "!AI_KEY!"=="" (
        echo   [ERROR] API Key tidak boleh kosong
        goto :ai_key
    )

    :: AI Model
    set /p AI_MODEL="  AI Model [gemini/gemini-2.5-flash-lite]: "
    if "!AI_MODEL!"=="" set AI_MODEL=gemini/gemini-2.5-flash-lite

    :: Admin ID
    :admin_id
    set /p ADMIN_ID="  Telegram Admin ID: "
    if "!ADMIN_ID!"=="" (
        echo   [ERROR] Admin ID tidak boleh kosong
        goto :admin_id
    )

    :: Timezone
    set /p TIMEZONE="  Timezone [Asia/Makassar]: "
    if "!TIMEZONE!"=="" set TIMEZONE=Asia/Makassar

    :: Renungan Time
    set /p RENUNGAN_TIME="  Renungan Time [08:00]: "
    if "!RENUNGAN_TIME!"=="" set RENUNGAN_TIME=08:00

    :: Write .env
    (
        echo # ============================================
        echo # Generated by setup wizard
        echo # ============================================
        echo.
        echo TIMEZONE=!TIMEZONE!
        echo.
        echo # Telegram Bot
        echo TELEGRAM_BOT_TOKEN=!T... echo.
        echo # AI Provider - Custom
        echo AI_API_KEY=!AI_KE... echo AI_API_ENDPOINT=!AI_ENDPOINT!
        echo AI_MODEL=!AI_MODEL!
        echo.
        echo # Renungan
        echo RENUNGAN_GROUP_ID=
        echo RENUNGAN_TIME=!RENUNGAN_TIME!
    ) > .env

    echo   [OK] .env written
)

:: ============================================
:: STEP 3: Cloudflare Tunnel (Optional)
:: ============================================
echo.
echo --- Step 3/5: Cloudflare Tunnel Setup ---
echo.

set WEBHOOK_URL=

if "!HAS_CLOUDFLARED!"=="true" (
    set /p setup_cf="  Setup Cloudflare Tunnel? (Y/n): "
    if /i "!setup_cf!" neq "n" (
        goto :setup_tunnel
    ) else (
        echo   [INFO] Skipping tunnel (will use polling mode)
    )
) else (
    set /p install_cf="  Install cloudflared and setup tunnel? (y/N): "
    if /i "!install_cf!"=="y" (
        echo.
        echo   [INFO] Downloading cloudflared...
        echo   Download from: https://github.com/cloudflare/cloudflared/releases/latest
        echo   Or install via: winget install cloudflare.cloudflared
        echo.
        where winget >nul 2>nul
        if !ERRORLEVEL! equ 0 (
            winget install cloudflare.cloudflared --accept-package-agreements --accept-source-agreements
            if !ERRORLEVEL! equ 0 (
                echo   [OK] cloudflared installed via winget
                set HAS_CLOUDFLARED=true
                goto :setup_tunnel
            ) else (
                echo   [WARN] winget install failed. Install manually from:
                echo   https://github.com/cloudflare/cloudflared/releases/latest
                goto :skip_tunnel
            )
        ) else (
            echo   [WARN] winget not available. Install manually from:
            echo   https://github.com/cloudflare/cloudflared/releases/latest
            goto :skip_tunnel
        )
    ) else (
        echo   [INFO] Skipping tunnel (will use polling mode)
    )
)
goto :skip_tunnel

:setup_tunnel
echo.
echo   [INFO] Opening browser for Cloudflare login...
echo   Please authorize cloudflared in your browser
echo.

cloudflared tunnel login
if %ERRORLEVEL% neq 0 (
    echo   [ERROR] Cloudflare login failed
    goto :skip_tunnel
)
echo   [OK] Cloudflare authorized!

:: Create tunnel
set TUNNEL_NAME=wa-renungan

:: Check existing tunnel
cloudflared tunnel list 2>nul | findstr "%TUNNEL_NAME%" >nul 2>nul
if %ERRORLEVEL% equ 0 (
    echo   [WARN] Tunnel '%TUNNEL_NAME%' already exists
    echo   [OK] Using existing tunnel
) else (
    echo   [INFO] Creating tunnel: %TUNNEL_NAME%
    cloudflared tunnel create %TUNNEL_NAME%
    if %ERRORLEVEL% neq 0 (
        echo   [ERROR] Failed to create tunnel
        goto :skip_tunnel
    )
    echo   [OK] Tunnel created
)

:: Get domain input
echo.
set /p DOMAIN="  Domain (contoh: example.com): "
if "!DOMAIN!"=="" (
    echo   [ERROR] Domain required
    goto :skip_tunnel
)

set /p SUBDOMAIN="  Subdomain [wa-bot]: "
if "!SUBDOMAIN!"=="" set SUBDOMAIN=wa-bot
set FULL_HOSTNAME=!SUBDOMAIN!.!DOMAIN!

:: Route DNS
echo   [INFO] Routing DNS: !FULL_HOSTNAME!
cloudflared tunnel route dns %TUNNEL_NAME% !SUBDOMAIN! 2>nul
echo   [OK] DNS routed

:: Get tunnel ID
for /f "tokens=1" %%a in ('cloudflared tunnel list ^| findstr "%TUNNEL_NAME%"') do set TUNNEL_ID=%%a

:: Write config
set CONFIG_DIR=%USERPROFILE%\.cloudflared
(
    echo tunnel: !TUNNEL_ID!
    echo credentials-file: %CONFIG_DIR%\!TUNNEL_ID!.json
    echo.
    echo ingress:
    echo   - hostname: !FULL_HOSTNAME!
    echo     service: http://localhost:3000
    echo   - service: http_status:404
) > "%CONFIG_DIR%\config.yml"
echo   [OK] config.yml written

:: Install as Windows service
echo   [INFO] Installing cloudflared as Windows service...
cloudflared service install
if %ERRORLEVEL% equ 0 (
    echo   [OK] Service installed
    net start cloudflared 2>nul
    echo   [OK] Service started
) else (
    echo   [WARN] Service install failed (may need Admin rights)
    echo   Run as Administrator or start manually:
    echo   cloudflared tunnel run %TUNNEL_NAME%
)

:: Update .env
set WEBHOOK_URL=https://!FULL_HOSTNAME!

:: Add WEBHOOK_URL to .env
echo. >> .env
echo # Webhook (Cloudflare Tunnel) >> .env
echo WEBHOOK_URL=!WEBHOOK_URL! >> .env
echo WEBHOOK_PORT=3000 >> .env

echo   [OK] Webhook URL: !WEBHOOK_URL!
goto :step4

:skip_tunnel
echo   [INFO] Using polling mode

:: ============================================
:: STEP 4: Bot Setup
:: ============================================
:step4
echo.
echo --- Step 4/5: Bot Setup ---
echo.

:: npm install
if exist "node_modules" (
    echo   [INFO] node_modules exists. Checking...
    npm ls --depth=0 >nul 2>nul
    if !ERRORLEVEL! equ 0 (
        echo   [OK] Dependencies already installed
    ) else (
        echo   [INFO] Reinstalling dependencies...
        call npm install --production
        echo   [OK] Dependencies installed
    )
) else (
    echo   [INFO] Installing dependencies...
    call npm install --production
    echo   [OK] Dependencies installed
)

:: Create logs directory
if not exist "logs" mkdir logs
echo   [OK] Logs directory ready

:: Test AI
echo   [INFO] Testing AI connection...
node -e "require('dotenv').config({override:true});const ai=require('./src/services/aiService');ai.testAIConnection().then(r=>{if(r.success)console.log('OK:'+r.provider+':'+r.model);else console.log('FAIL:'+(r.error||'unknown'))}).catch(e=>console.log('FAIL:'+e.message))" 2>nul
echo.

:: ============================================
:: STEP 5: Done!
:: ============================================
echo --- Step 5/5: Setup Complete! ---
echo.

if defined WEBHOOK_URL (
    set MODE=WEBHOOK (hemat ~70%% bandwidth^)
) else (
    set MODE=POLLING (~750MB/month^)
)

echo ╔═══════════════════════════════════════════════════╗
echo ║  Setup Complete!                                  ║
echo ╠═══════════════════════════════════════════════════╣
if defined WEBHOOK_URL (
    echo ║  Webhook:  %WEBHOOK_URL%
)
echo ║  Mode:     %MODE%
echo ╠═══════════════════════════════════════════════════╣
echo ║                                                   ║
echo ║  Jalankan:                                        ║
echo ║    npm start                                      ║
echo ║    atau: pm2 start ecosystem.config.js            ║
echo ║                                                   ║
echo ║  Reset: del .setup-state ^& setup.bat              ║
echo ║                                                   ║
echo ╚═══════════════════════════════════════════════════╝
echo.

:: Cleanup state
if exist "%STATE_FILE%" del "%STATE_FILE%"

goto :eof

:fail
echo.
echo [ERROR] Setup failed. Fix the issues above and run again.
exit /b 1
